name: fws_dashboard_produccion
description: Proyecto privado para Fusion Welding Solutions.

# ðŸ¤ Â¿Quieres colaborar? / Want to contribute?
# Â¡Este proyecto estÃ¡ iniciando y estamos abiertos a nuevas ideas!
# Si quieres colaborar en diseÃ±o, desarrollo o anÃ¡lisis, contÃ¡ctame por correo o por redes.
# Todo aporte que ayude a la industria y a la excelencia operativa es bienvenido.

# ðŸ›¡ï¸ Licencia
# Este proyecto estÃ¡ bajo licencia privada para Fussion Welding Solution.
# Uso externo requiere autorizaciÃ³n expresa.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.1
  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
